version: '2'

services:
    react:
      container_name: react
      build: ./
      restart: unless-stopped
      ports:
        - "3000:3000"
        # - "24678:24678"
      volumes:
        - ./:/app

networks:
    default:
        driver: bridge