const timezoneMapping = {
    'SST': 'Pacific/Midway',
    'HST': 'Pacific/Honolulu',
    'AKDT': 'America/Anchorage',
    'PST': 'America/Whitehorse',
    'MST': 'America/Phoenix',
    'PDT':'America/Tijuana',
    'PST':'America/Los_Angeles',
    'MST':'America/Denver',
    'MST':'America/Chihuahua',
    'CST':'America/Regina',
    'CST': 'America/Mexico_City',
    'CST': 'America/Belize',
    'CST':'America/Chicago',
    'COT':'America/Bogota',
    'EST':'America/New_York',
    'VET':'America/Caracas',
    'CLT': 'America/Santiago',
    'BRT': 'America/Sao_Paulo',
    'UYT':'America/Montevideo',
    'ART':'America/Argentina/Buenos_Aires',
    'NST':'America/St_Johns',
    'WGT':'America/Godthab',
    'CVT':'Atlantic/Cape_Verde',
    'AZOT':'Atlantic/Azores',
    'UTC':'UTC+0:00',
    'WEST': 'Africa/Casablanca',
    'BST': 'Europe/London',
    'IST':'Europe/Dublin',
    'WEST':'Europe/Lisbon',
    'WEST':'Atlantic/Canary',
    'WAT':'Africa/Lagos',
    'CEST': 'Europe/Belgrade',
    'CET': 'Europe/Sarajevo',
    'CET': 'Europe/Brussels',
    'CEST': 'Europe/Amsterdam',
    'EET':'Africa/Cairo',
    'CAT': 'Africa/Harare',
    'EET': 'Europe/Bucharest',
    'EET':'Europe/Helsinki',
    'EET':'Europe/Athens',
    'IST':'Asia/Jerusalem',
    'MSK': 'Europe/Moscow',
    'AST':'Asia/Kuwait',
    'EAT':'Africa/Nairobi',
    'AST': 'Asia/Baghdad',
    'IRST':'Asia/Tehran',
    'GST':'Asia/Dubai',
    'AZT': 'Asia/Baku',
    'AFT':'Asia/Kabul',
    'YEKT':'Asia/Yekaterinburg',
    'PKT':'Asia/Karachi',
    'IST': 'Asia/Kolkata',
    'IST': 'Asia/Colombo',
    'NPT': 'Asia/Kathmandu',
    'BDT': 'Asia/Dhaka',
    '+06': 'Asia/Almaty',
    'MMT': 'Asia/Yangon',
    'ICT': 'Asia/Bangkok',
    'KRAT':'Asia/Krasnoyarsk',
    'CST':'Asia/Shanghai',
    'MYT':'Asia/Kuala_Lumpur',
    'CST': 'Asia/Taipei',
    'AWST':'Australia/Perth',
    'IRKT': 'Asia/Irkutsk',
    'KST': 'Asia/Seoul',
    'JST': 'Asia/Tokyo',
    'YAKT': 'Asia/Yakutsk',
    'ACST': 'Australia/Darwin',
    'ACST': 'Australia/Adelaide',
    'AEST': 'Australia/Sydney',
    'AEST': 'Australia/Brisbane',
    'AEST': 'Australia/Hobart',
    'VLAT': 'Asia/Vladivostok',
    'ChST':'Pacific/Guam',
    'MAGT': 'Asia/Magadan',
    'PETT': 'Asia/Kamchatka',
    'FJT':'Pacific/Fiji',
    'NZST': 'Pacific/Auckland',
    'TST': 'Pacific/Tongatapu'
  };

  export {timezoneMapping};